<?php

    namespace thebuggenie\modules\mobile;

use thebuggenie\core\framework;

    /**
     * Autogenerated module Mobile
     *
     * @author
     * @version 0.1
     * @license http://www.opensource.org/licenses/mozilla1.1.php Mozilla Public License 1.1 (MPL 1.1)
     * @package mobile
     * @subpackage core
     */

    /**
     * Autogenerated module Mobile
     *
     * @package mobile
     * @subpackage core
     *
     * @Table(name="\thebuggenie\core\entities\tables\Modules")
     */
    class Mobile extends \thebuggenie\core\entities\Module
    {

        const VERSION = '0.1';

        protected $_name = 'mobile';
        protected $_longname = 'Mobile';
        protected $_module_config_title = 'Mobile';
        protected $_module_config_description = 'Mobile - flexible layout for tablet and mobile';
        protected $_description = 'Mobile - flexible layout for tablet and mobile';
        
        protected function _initialize()
        {
        }

        protected function _addAvailablePermissions()
        {
        }

        protected function _addListeners()
        {
            framework\Event::listen('core', 'layout.php::header-begins', array($this, 'addMobileContent'));
//            framework\Event::listen('core', 'header_submenu_decider', array($this, 'hideTopMenu'));
//            framework\Event::listen('core', 'header_mainmenu_decider', array($this, 'hideTopMenu'));
//            framework\Event::listen('core', 'header_usermenu_decider', array($this, 'hideTopMenu'));
            framework\Event::listen('core', 'header_before_logo', array($this, 'addMobileMenuAnchor'));
            framework\Event::listen('core', 'header_menu_end', array($this, 'addMobileMenu'));
            framework\Event::listen('core', 'viewissue_left_bottom', array($this, 'disableDetailsResizing'));
        }

        protected function _install($scope)
        {
            if ($scope == framework\Settings::getDefaultScopeID()) {
                $mobile_css_path = THEBUGGENIE_PATH . THEBUGGENIE_PUBLIC_FOLDER_NAME . DS . 'css' . DS . 'mobile.css';
                if (!is_writable(pathinfo($mobile_css_path, PATHINFO_DIRNAME))) {
                    throw new framework\exceptions\ConfigurationException("Cannot save the file {$mobile_css_path}", framework\exceptions\ConfigurationException::PERMISSION_DENIED);
                }
                if (file_exists($mobile_css_path)) {
                    unlink($mobile_css_path);
                }
                symlink(THEBUGGENIE_MODULES_PATH . 'mobile' . DS . 'css' . DS . 'mobile.css', $mobile_css_path);
            }
        }

        protected function _loadFixtures($scope)
        {
        }

        protected function _uninstall()
        {
            if (framework\Context::getScope()->isDefault()) {
                $filename = THEBUGGENIE_PATH . THEBUGGENIE_PUBLIC_FOLDER_NAME . DS . 'css' . DS . 'mobile.css';
                if (file_exists($filename)) {
                    unlink($filename);
                }
            }
        }

        public function addMobileContent(framework\Event $event)
        {
            include_component('mobile/header');
        }

        public function addMobileMenuAnchor(framework\Event $event)
        {
            include_component('mobile/menuanchor');
        }

        public function addMobileMenu(framework\Event $event)
        {
            include_component('mobile/menu');
            include_component('mobile/usermenu');
        }

        public function hideTopMenu(framework\Event $event)
        {
            $event->setReturnValue(false);
        }

        public function disableDetailsResizing(framework\Event $event)
        {
            include_component('mobile/disableissuedetailsresizing');
        }
    }
